# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6a7803af0d8ec52d0e719e42eae303d787b7eba4a612bf32c91b68596bb3015c0a3191bcb7976fbf4f8b5321768fba87dcc095cb8e3be5b00a4d2d13175cbb1d

test:
  secret_key_base: d0756f1ed2b7c20cb535f65a8595848a8addfab63996c2d72f9eb929ed82d1c636e189d5ac3a976efec45874c2f8b32d9213a33b5510cbb225abd5fcee8c193e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
